mongo:
  uri: mongodb://mongo:27017/person?readPreference=primary&connectTimeoutMS=5000&socketTimeoutMS=5000
  database: person
  collection: person
port: 3000
log:
  level: info
  jsonformatter: false